### ISSUE TITLE
Türkçe harflerle request

### ISSUE THREAD

**Issue by kaze-kun** [Sensei-911/word#1]
Eğer yazılan kelimenin içinde "İ" veya herhangi büyük bir türkçe harfi varsa request başarısız olup kelimeyi tanımıyor.

**Comment by kaze-kun** [comment]
Sensei can you check up?

**Comment by Sensei-911** [comment]
Şu an yayında olan kod eskimiş ve düzenlenmiş hali yazıldı. En yakın zamanda güncellerim. 
Sorunuza gelirse @kaze-kun 57 ve 63.cü satırdaki "message.content" yazısını message.content.toLowerCase() olarak değiştirin lütfen.
